

name: Deploy on EC2

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: build repo
              run: |
                    npm install
                    npm run build

            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/Key1
                chmod 600 ~/.ssh/Key1
                ssh-keyscan -H ${{secrets.EC2_IP}} >> ~/.ssh/known_hosts

            - name: SSH Connection & Cleanup
              run: |
                    ssh -i ~/.ssh/Key1 ${{secrets.EC2_USER}}@${{secrets.EC2_IP}} << 'ENDSSH'
                        sudo yum update -y
                        sudo yum upgrade -y
                        sudo yum install -y git nodejs
                        sudo npm install -g serve
                        sudo yum rm -rf ~/build
                    ENDSSH

            - name: SCP
              run: |
                    scp -i ~/.ssh/Key1 -r build ${{secrets.EC2_USER}}@${{secrets.EC2_IP}}:/home/${{secrets.EC2_USER}}/build

            - name: Start App
              run: |
                    ssh -i ~/.ssh/Key1 ${{secrets.EC2_USER}}@${{secrets.EC2_IP}} << 'ENDSSH'
                        sudo server -l 80 -s ~/build
                    ENDSSH