

name: Deploy on EC2

on: push

env:
    PATH_KEY: ~/.ssh

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: build repo
              run: |
                    npm install
                    npm run build

            - name: Setup SSH
              run: |
                    mkdir -p ${{env.PATH_KEY}}
                    echo "${{secrets.SSH_KEY}}" > ${{env.PATH_KEY}}/Key1
                    chmod 600 ${{env.PATH_KEY}}/Key1
                    ssh-keyscan -H ${{secrets.EC2_IP}} >> ${{env.PATH_KEY}}/known_hosts

            - name: SSH Connection & Cleanup
              run: |
                    ssh -i ${{env.PATH_KEY}}/Key1 ${{secrets.EC2_USER}}@${{secrets.EC2_IP}} << 'ENDSSH'
                        sudo yum update -y
                        sudo yum upgrade -y
                        sudo yum install -y git nodejs
                        sudo npm install -g serve
                        sudo rm -rf ~/build
                    ENDSSH

            - name: SCP
              run: |
                    scp -i ${{env.PATH_KEY}}/Key1 -r build ${{secrets.EC2_USER}}@${{secrets.EC2_IP}}:/home/${{secrets.EC2_USER}}/build

            - name: Start App
              run: |
                    ssh -i ${{env.PATH_KEY}}/Key1 ${{secrets.EC2_USER}}@${{secrets.EC2_IP}} << 'ENDSSH'
                        sudo serve -l 80 -s ~/build
                    ENDSSH